function gerar() {
    let perguntas = [
        'Eu nunca tive um sonho romântico com alguém que está aqui.' ,
        'Eu nunca comprei um "brinquedo de estimulação".' ,
        'Eu nunca fui pego me masturbando".' ,
        'Nunca me senti atraído(a) pelo pai/mãe de algum amigo.' ,
        'Nunca ninguém dançou no meu colo.' ,
        'Eu nunca enviei fotos sem roupa para a pessoa errada.' ,
        'Eu nunca fingi prazer.' ,
        'Nunca fiquei com alguém do mesmo gênero que eu.' ,
        'Eu nunca fiquei com mais de uma pessoa ao mesmo tempo.' ,
        'Eu nunca tirei a roupa enquanto dançava para alguém.' ,
        'Eu nunca gravei vídeo enquanto estava ficando com alguém.' ,
        'Eu nunca fui em um brega.' ,
        'Eu nunca mandei fotos sem roupa para alguém.' ,
        'Nunca quis ficar com um casal de amigos.' ,
        'Eu nunca marquei de ficar com alguém do Tinder.' ,
        'Eu nunca tirei a roupa em uma festa.' ,
        'Eu nunca tive um "amigo colorido" ou "amigo com benefícios".' ,
        'Nunca vi meus pais em situações de intimidade extrema.' ,
        'Eu nunca tive um sonho intímo com algum professor.' ,
        'Eu nunca fiquei com alguém desta roda.' ,
        'Eu nunca fiquei com alguém que eu nem sabia o nome.' ,
        'Eu nunca fiquei com uma pessoa e depois nunca mais falei com ela.' ,
        'Eu nunca fiquei com alguém na cama dos meus pais.' ,
        'Eu nunca transei com alguém na rua.' ,
        'Eu nunca assisti outra pessoa transando.' ,
        'Eu nunca dancei no colo de ninguém.' ,
        'Eu nunca transei na praia.' ,
        'Nunca disse eu te amo apenas para ficar com alguém.' ,
        'Nunca dormi enquanto estava no meio de uma situação de intimidade com alguém.' ,
        'Eu nunca fiquei com alguém no banheiro de uma festa.' ,
        'Nunca fiquei com alguém 20 anos mais velho que eu.' ,
        'Nunca usei uma fantasia ousada.' ,
        'Eu nunca usei o Tinder enquanto namorava.' ,
        'Nunca usei nenhum objeto para me dar prazer.' ,
        'Eu nunca quis ver meu parceiro ficando com outra pessoa.' ,
        'Eu nunca enfiei o dedo em mim mesmo(a).' ,
        'Eu nunca… recebi lapdance.', 
        'Eu nunca… gravei uma sextape (vídeo transando).', 
        'Eu nunca… transei com alguém desta roda.', 
        'Eu nunca… fiz lapdance.', 
        'Eu nunca… fingi um orgasmo.', 
        'Eu nunca… transei na cama dos meus pais.', 
        'Eu nunca… fiz striptease para alguém.', 
        'Eu nunca… fiz sexo com mais de uma pessoa ao mesmo tempo.', 
        'Eu nunca… comprei um brinquedo erótico.', 
        'Eu nunca… tive um sonho erótico com alguém que está aqui.', 
        'Eu nunca… tive um sexbuddy (amigo colorido/amigo com benefícios).', 
        'Eu nunca… fui pego assistindo pornô.', 
        'Eu nunca… transei com alguém do mesmo sexo.', 
        'Eu nunca… transei na rua.', 
    ];

   var a = Math.random() * 49;
   var sorteio = Math.round(a);
    resultado.innerHTML = `${perguntas[sorteio]}`;



}